// Generated by gencpp from file snake_msgs/SnakeSlaveMCUError.msg
// DO NOT EDIT!


#ifndef SNAKE_MSGS_MESSAGE_SNAKESLAVEMCUERROR_H
#define SNAKE_MSGS_MESSAGE_SNAKESLAVEMCUERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace snake_msgs
{
template <class ContainerAllocator>
struct SnakeSlaveMCUError_
{
  typedef SnakeSlaveMCUError_<ContainerAllocator> Type;

  SnakeSlaveMCUError_()
    : timestamp()
    , mcu_id(0)
    , reseted_by_power_on(false)
    , reseted_by_software(false)
    , reseted_by_low_power(false)
    , reseted_by_watch_dog_timer(false)
    , voltage(false)  {
    }
  SnakeSlaveMCUError_(const ContainerAllocator& _alloc)
    : timestamp()
    , mcu_id(0)
    , reseted_by_power_on(false)
    , reseted_by_software(false)
    , reseted_by_low_power(false)
    , reseted_by_watch_dog_timer(false)
    , voltage(false)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _mcu_id_type;
  _mcu_id_type mcu_id;

   typedef uint8_t _reseted_by_power_on_type;
  _reseted_by_power_on_type reseted_by_power_on;

   typedef uint8_t _reseted_by_software_type;
  _reseted_by_software_type reseted_by_software;

   typedef uint8_t _reseted_by_low_power_type;
  _reseted_by_low_power_type reseted_by_low_power;

   typedef uint8_t _reseted_by_watch_dog_timer_type;
  _reseted_by_watch_dog_timer_type reseted_by_watch_dog_timer;

   typedef uint8_t _voltage_type;
  _voltage_type voltage;




  typedef boost::shared_ptr< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> const> ConstPtr;

}; // struct SnakeSlaveMCUError_

typedef ::snake_msgs::SnakeSlaveMCUError_<std::allocator<void> > SnakeSlaveMCUError;

typedef boost::shared_ptr< ::snake_msgs::SnakeSlaveMCUError > SnakeSlaveMCUErrorPtr;
typedef boost::shared_ptr< ::snake_msgs::SnakeSlaveMCUError const> SnakeSlaveMCUErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snake_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'snake_msgs': ['/home/snake/catkin_ws/src/snake_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec4a0033a8ccadf04d99caa8e4a4ea13";
  }

  static const char* value(const ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec4a0033a8ccadf0ULL;
  static const uint64_t static_value2 = 0x4d99caa8e4a4ea13ULL;
};

template<class ContainerAllocator>
struct DataType< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snake_msgs/SnakeSlaveMCUError";
  }

  static const char* value(const ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "###########################################################\n\
# MCUのエラーの内容に関するmsg型\n\
# エラーが起きているところがtrue\n\
###########################################################\n\
\n\
time timestamp\n\
uint8 mcu_id\n\
bool reseted_by_power_on\n\
bool reseted_by_software\n\
bool reseted_by_low_power\n\
bool reseted_by_watch_dog_timer\n\
bool voltage\n\
";
  }

  static const char* value(const ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.mcu_id);
      stream.next(m.reseted_by_power_on);
      stream.next(m.reseted_by_software);
      stream.next(m.reseted_by_low_power);
      stream.next(m.reseted_by_watch_dog_timer);
      stream.next(m.voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SnakeSlaveMCUError_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snake_msgs::SnakeSlaveMCUError_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "mcu_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mcu_id);
    s << indent << "reseted_by_power_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reseted_by_power_on);
    s << indent << "reseted_by_software: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reseted_by_software);
    s << indent << "reseted_by_low_power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reseted_by_low_power);
    s << indent << "reseted_by_watch_dog_timer: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reseted_by_watch_dog_timer);
    s << indent << "voltage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKE_MSGS_MESSAGE_SNAKESLAVEMCUERROR_H
