(cl:in-package snake_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          IMU_INDEX-VAL
          IMU_INDEX
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          RPY_IS_UPDATED-VAL
          RPY_IS_UPDATED
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          GYRO_IS_UPDATED-VAL
          GYRO_IS_UPDATED
          ACCEL_X-VAL
          ACCEL_X
          ACCEL_Y-VAL
          ACCEL_Y
          ACCEL_Z-VAL
          ACCEL_Z
          ACCEL_IS_UPDATED-VAL
          ACCEL_IS_UPDATED
))