(cl:defpackage snake_msgs-msg
  (:use )
  (:export
   "<SNAKE_JOINT_DATA4V2>"
   "SNAKE_JOINT_DATA4V2"
   "<SNAKEIMUDATA>"
   "SNAKEIMUDATA"
   "<SNAKECOPCOMMAND>"
   "SNAKECOPCOMMAND"
   "<SNAKE_JOINT_COMMAND4V2>"
   "SNAKE_JOINT_COMMAND4V2"
   "<SNAKEJOINTERROR>"
   "SNAKEJOINTERROR"
   "<SNAKE_JOINT_COMMAND>"
   "SNAKE_JOINT_COMMAND"
   "<SNAKE_JOINT_DATA>"
   "SNAKE_JOINT_DATA"
   "<SNAKESLAVEMCUERROR>"
   "SNAKESLAVEMCUERROR"
   "<SNAKECOPDATA>"
   "SNAKECOPDATA"
   "<SNAKEIMUCOMMAND>"
   "SNAKEIMUCOMMAND"
   "<SNAKESLAVEMCUDATA>"
   "SNAKESLAVEMCUDATA"
  ))

