# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from snake_msgs/SnakeCOPCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SnakeCOPCommand(genpy.Message):
  _md5sum = "0f653502197b950088dfaf6371a5c617"
  _type = "snake_msgs/SnakeCOPCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """###########################################################
# ロボットにCOP Sensor関係のデータを要求するためのmsg型
# 必要なデータの形式に関するread_*trueにする
###########################################################

uint8 cop_index
bool target_all
bool read_data

"""
  __slots__ = ['cop_index','target_all','read_data']
  _slot_types = ['uint8','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cop_index,target_all,read_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SnakeCOPCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.cop_index is None:
        self.cop_index = 0
      if self.target_all is None:
        self.target_all = False
      if self.read_data is None:
        self.read_data = False
    else:
      self.cop_index = 0
      self.target_all = False
      self.read_data = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.cop_index, _x.target_all, _x.read_data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.cop_index, _x.target_all, _x.read_data,) = _struct_3B.unpack(str[start:end])
      self.target_all = bool(self.target_all)
      self.read_data = bool(self.read_data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.cop_index, _x.target_all, _x.read_data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.cop_index, _x.target_all, _x.read_data,) = _struct_3B.unpack(str[start:end])
      self.target_all = bool(self.target_all)
      self.read_data = bool(self.read_data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B = struct.Struct("<3B")
