(cl:in-package joy_handler_hori-msg)
(cl:export '(JOY_STICK_R_X_RIGHTWARDS-VAL
          JOY_STICK_R_X_RIGHTWARDS
          JOY_STICK_R_Y_UPWARDS-VAL
          JOY_STICK_R_Y_UPWARDS
          JOY_STICK_L_X_RIGHTWARDS-VAL
          JOY_STICK_L_X_RIGHTWARDS
          JOY_STICK_L_Y_UPWARDS-VAL
          JOY_STICK_L_Y_UPWARDS
          CROSS_KEY_RIGHT-VAL
          CROSS_KEY_RIGHT
          CROSS_KEY_LEFT-VAL
          CROSS_KEY_LEFT
          CROSS_KEY_UP-VAL
          CROSS_KEY_UP
          CROSS_KEY_DOWN-VAL
          CROSS_KEY_DOWN
          BUTTON_CIRCLE-VAL
          BUTTON_CIRCLE
          BUTTON_TRIANGLE-VAL
          BUTTON_TRIANGLE
          BUTTON_CROSS-VAL
          BUTTON_CROSS
          BUTTON_SQUARE-VAL
          BUTTON_SQUARE
          BUTTON_R1-VAL
          BUTTON_R1
          BUTTON_R2-VAL
          BUTTON_R2
          BUTTON_R3-VAL
          BUTTON_R3
          BUTTON_L1-VAL
          BUTTON_L1
          BUTTON_L2-VAL
          BUTTON_L2
          BUTTON_L3-VAL
          BUTTON_L3
          BUTTON_SELECT-VAL
          BUTTON_SELECT
          BUTTON_START-VAL
          BUTTON_START
          BUTTON_PS-VAL
          BUTTON_PS
))